version: '3'
services:
  backend-service:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: always
    environment:
      DBHOST: db
      DBPASSWORD: "F20ItOnk123"
    depends_on:
      - db
      
  frontend-service:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      F21DISPBACKEND_SERVICE_HOST: backend-service
      F21DISPBACKEND_PORT_8080_TCP_PORT: 80
    ports: 
      - "8080:80"
    depends_on:
      - backend-service

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "F20ItOnk123"