apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql19-disp-gr6
  labels:
    app: mssql-gr6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-gr6
  template:
    metadata:
      labels:
        app: mssql-gr6
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mssql-gr6
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "F20ItOnk123" 
        - name: MSSQL_DATA_DIR
          value: /var/opt/mssql/mdf
        - name: MSSQL_LOG_DIR
          value: /var/opt/mssql/ldf          
        volumeMounts:
        - name: mssql-base-volume
          mountPath: /var/opt/mssql
      volumes:
      - name: mssql-base-volume
        persistentVolumeClaim:
          claimName: mssql-base-volume
---
apiVersion: v1
kind: Service
metadata:
  name: mssql19-disp-gr6-service
spec:
  selector:
    app: mssql-gr6
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer