version: '3'
services:
  backend:
    build: .
    restart: always
    ports: 
      - "8080:80"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "F20ItOnk123"
    ports:
      - "1433:1433"